### ISSUE TITLE
Windows release compilation broken

### ISSUE THREAD

**Issue by BlueAndi** [grodansparadis/vscp_software#97]
Hi Ake,

can you please check that? The debug version is running, but the release version miss a wx/setup.h and etc.

I use the vscp_project.sln

Best regards
Andreas

**Comment by grodansparadis** [comment]
You must compile the wxlib in both debug and release versions otherwise 
you will get this error.

Andreas Merkle skrev den 2015-03-02 18:25:
>
> Hi Ake,
>
> can you please check that? The debug version is running, but the 
> release version miss a wx/setup.h and etc.
>
> Best regards
> Andreas
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/97>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
http://www.avast.com

**Comment by BlueAndi** [comment]
Good hint, I will check that tomorrow.

**Comment by BlueAndi** [comment]
You were right, that was the problem.
